apiVersion: v1
kind: Pod
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  containers:
    - name: testapp
      image: localhost:5000/testapp:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      envFrom:
        - configMapRef:
            name: testapp-config
